openapi: 3.0.3
info:
  title: 'DFCU Loans API'
  description: 'An API to check and view outstanding loans per user account'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/outstanding-loans:
    post:
      summary: 'Outstanding Loans'
      operationId: outstandingLoans
      description: "This endpoint allows you to fetch all outstanding Loans attached to an account number.\n\nCheck that the service is up. If everything is okay, you'll get a 200 OK response.\nOtherwise, the request will fail with an error code such as 400, 422, 500 and a response listing the error message.\n<aside class=\"info\"><b>You can use these test account numbers.</b><br>\n1000000001 => Returns outstanding loans<br>\n1000000002 => Return no outstanding loan</aside>"
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {ACCESS_TOKEN}'
          schema:
            type: string
      responses:
        200:
          description: 'Found outstanding Loans'
          content:
            text/plain:
              schema:
                type: string
                example: "[\n{\n\"amount_disbursed\": 9007000,\n\"outstanding_amount\": 8976000,\n\"date_disbursed\": \"2018-05-09 10:10:57\",\n\"due_date\": \"2031-07-09 10:10:57\",\n\"created_at\": \"2023-04-09T10:10:57.000000Z\",\n\"updated_at\": \"2023-04-09T10:10:57.000000Z\",\n}\n]"
        422:
          description: 'Account Number Validation errors'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The account number field must be 10 digits.'
                  errors:
                    account_number:
                      - 'The account number field must be 10 digits.'
                properties:
                  message:
                    type: string
                    example: 'The account number field must be 10 digits.'
                  errors:
                    type: object
                    properties:
                      account_number:
                        type: array
                        example:
                          - 'The account number field must be 10 digits.'
                        items:
                          type: string
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_number:
                  type: string
                  description: 'Must be 10 digits.'
                  example: '4755959177'
              required:
                - account_number
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
